export const SET_MENULIST = 'SET_MENULIST'

export const SET_ORIGINMENULIST = 'SET_ORIGINMENULIST'

export const SET_ISLOADING = 'SET_ISLOADING'

export const SET_BREADCRUMBPATH = 'SET_BREADCRUMBPATH'

export const SET_DISPLAYNAME = 'SET_DISPLAYNAME'

export const SET_AUTHORIZE = 'SET_AUTHORIZE'

export const SET_AUTHINFO = 'SET_AUTHINFO'

export const SET_ISROOT = 'SET_ISROOT'

export const SET_ISTEST = 'SET_ISTEST'

export const SET_ISNOOPERATION = 'SET_ISNOOPERATION'

export const SET_ERRTIPCODE = "SET_ERRTIPCODE"
